services:
  bridge-service:
    build:
      context: .
      args:
        - GITHUB_USERNAME=${GITHUB_USERNAME}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - "8081:8081"
    env_file:
      - .env